	<div  class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
		<div class="header-titulos"> Agregar y modificar una partidas </div>
		
		<div class="">

			<form class="form-horizontal" id="form_partida" autocomplete="off">
			  
			  <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Partida</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="partida" name="partida" placeholder="ejemp 4.01.01.01.00">
			    </div>
			  </div>

			    <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Denominación</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="denominacion" name="denominacion" placeholder="nombre de la partida">
			    </div>
			  </div>

			    <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Saldo inicial</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="saldo" name="saldo" placeholder="cantidad expresada en Bs." data-a-sign="Bs " data-a-dec="," data-a-sep=".">
			    </div>
			  </div>

			
			
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <button type="button" id="guardar" class="btn btn-default">Guardar</button>
			      <button type="button" id="actualizar" class="btn btn-default" disabled="true">Actualizar</button>
			      <button type="button" id="limpiar" class="btn btn-default" disabled="true">Limpiar</button>
			      <button type="button" id="atras" class="btn btn-default" onclick="history.back()">Atras</button>
			    </div>
			  </div>
			</form>


			
		</div>

	</div>