	<div  class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
		<div class="header-titulos"> lista de partidas cargadas </div>
		
		<div class="">

			

<table class="table">
<tr>
	<td>partida</td>
	<td>denominacion</td>
	<td>cantidad actual</td>
	<td>cantidad total</td>
</tr>
<?php for ($i=0; $i <count($this->partidas) ; $i++):?>


<tr>
	<td> <div id="infor_partida" data-partida="<?php echo $this->partidas[$i]["partida"] ?>" data-toggle="tooltip" data-placement="top" title="detallar la partida" >  <?php echo $this->partidas[$i]["partida"] ?> </div> </td>
	<td><div> </div><?php echo $this->partidas[$i]["denominacion"] ?></td>
	<td>Bs <?php echo number_format($this->partidas[$i]["saldo"], 2, ",", "."); ?></td>
	<td>Bs <?php echo number_format($this->partidas[$i]["saldo_total"], 2, ",", "."); ?></td>
</tr>








<?php endfor; ?>
</table>
			
		</div>

	</div>




	<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">detalles de la partida</h4>
      </div>
      <div id="tablaa" class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>