<div  class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
		<div class="header-titulos"> añadir creditos a partidas </div>
		

		<input id="partida" type="hidden" value="<?php echo $this->_partida['partida'] ?>">
		<input id="denominacion" type="hidden" value="<?php echo $this->_partida['denominacion'] ?>">
		<input id="saldo_t" type="hidden" value="<?php echo $this->_partida['saldo'] ?>">
		

		<div class="">

			<form class="form-horizontal" id="form_partida" autocomplete="off">
			  	
			 
			<div class="inforr">
			    <label for="" class="col-sm-10 col-sm-offset-2 ">partida: <?php echo $this->_partida['partida'] ?></label>
			   
			  </div>
			  <div class="inforr">
			    <label for="" class="col-sm-10 col-sm-offset-2 ">denominacion: <?php echo $this->_partida['denominacion'] ?></label>
			   
			  </div>
			  <div class="inforr">
			    <label for="" class="col-sm-10 col-sm-offset-2 ">saldo: <?php echo $this->_partida['saldo'] ?></label>
			   
			  </div>



			   <div class="form-group">
			    <label for="" class="col-sm-2 control-label">descripcion</label>
			    <div class="col-sm-10">
			      <textarea class="form-control" id="descripcion" name="descripcion"></textarea>
			    </div>
			  </div>
			   <div class="form-group">
			    <label for="" class="col-sm-2 control-label">monto a acreditar</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="saldo_d" name="saldo_d" placeholder="cantidad expresada en Bs." data-a-sign="Bs " data-a-dec="," data-a-sep=".">
			    </div>
			  </div>
			   

			
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <button type="button" id="guardar" class="btn btn-default">guardar</button>
			      
			      <button type="button" id="atras" class="btn btn-default" onclick="history.back()">atras</button>
			    </div>
			  </div>
			</form>


			
		</div>

	</div>


