	<div  class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
		<div class="header-titulos"> Agregar y modificar una requisicion </div>
		
		<div class="">

			<form class="form-horizontal" id="form_partida" autocomplete="off">
			  
			  <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Codigo de la Requisicion</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="codigo_requisicion" name="codigo_requisicion">
			    </div>
			  </div>

			  <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Nombre de la Requisicion</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="nombre_requisicion" name="nombre_requisicion">
			    </div>
			  </div>

			   <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Departamento</label>
			    <div class="col-sm-10">
			     <select id="select_departamentos">
			     	<option value="">---Seleccione--</option>
			     </select>
			    </div>
			  </div>
<div id="oculto">
			  <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Partida</label>
			    <div class="col-sm-10">
			     <select id="select_partidas">
			     	<option value="">---Seleccione--</option>
			     </select>
			    </div>
			  </div>

			  <div class="form-group">
			    <label  class="col-sm-2 control-label">Descripcion del producto</label>
			    <div class="col-sm-10">
			    <textarea id="descripcion" name="descripcion" ></textarea>
			    </div>
			  </div>
 			  
 			  <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Cantidad</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="cantidad" name="cantidad">
			    </div>
			  </div>

			   <div class="form-group">
			    <label for="" class="col-sm-2 control-label">Precio por unidad</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="precio" name="precio">
			    </div>
			  </div>
</div>
			   		
			
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="button" id="continuar" class="btn btn-default">Continuar</button>		      
					    <button type="button" id="guardar" class="btn btn-default">Cargar</button>
					    <button type="button" id="actualizar" class="btn btn-default" disabled="true">Actualizar</button>
					    <button type="button" id="limpiar" class="btn btn-default" disabled="true">Limpiar</button>					    
					    <button type="button" id="atras2" class="btn btn-default">Atras</button>
					    <button type="button" id="atras" class="btn btn-default" onclick="history.back()">Atras</button>
					    <button type="button" id="finalizar" class="btn btn-default">Finalizar</button>
					</div>
				</div>
			</form>


			
		</div>

		<div class="header-titulos"> Vsita previa de la requsicion </div>
		<div>
			<table id="previa" class="table table-striped">
				<tr>
					<td>Partida</td>
					<td>Descripcion</td>
					<td>Cantidad</td>
					<td>Precio Unitario</td>
					<td>Precio Total</td>
				</tr>
			</table>
		</div>

	</div>