	<div  class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
		<div class="header-titulos"> Lista de requisiciones cargadas </div>
		
		<div class="">

			

<table class="table">
<tr>
	<td>Codigo Requisicion</td>
	<td>Nombre Requisicion</td>
	<td>Departamento Solicitante</td>
	<td>Estado</td>
	<td>Acciones</td>

</tr>
<?php for ($i=0; $i <count($this->requisiciones) ; $i++):?>

<tr>
	<td><?php echo $this->requisiciones[$i]["codigo_requisicion"] ?></td>
	<td><?php echo $this->requisiciones[$i]["nombre_requisicion"]; ?></td>
	<td><?php echo $this->requisiciones[$i]["nombre_departamento"]; ?>  </td>
	<td><?php echo $this->requisiciones[$i]["estado_requisicion"]; ?></td>
	<td><div  data-toggle="tooltip" data-placement="top" title="Detallar la requisicion" >
	<span id="detalles_requisicion"  data-requisicion="<?php echo $this->requisiciones[$i]["id_requisicion"] ?>" class="glyphicon glyphicon-open-file" aria-hidden="true"></span></div></td> 
</tr>

   






<?php endfor; ?>
</table>
			
		</div>

	</div>




	<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Detalles de la Requisicion</h4>
      </div>
      <div id="tablaa" class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        
      </div>
    </div>
  </div>
</div>