	<div  class="">

		
		<div  class="col-sm-6 left">
			<img class="img-responsive img-lapis" width="100%" src="<?php echo BASE_URL?>public/img/cont.jpg" alt="">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, libero sapiente aliquam at consequuntur distinctio obcaecati, nihil excepturi eligendi repudiandae quibusdam odit fugiat sint fugit blanditiis praesentium, soluta hic nostrum.
		</div>
		<div  class="col-sm-6 right ">
			
			<div id="accordion">
			  <h3>Partidas</h3>
			  <div>
			    <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
			    <div>
			    	<div class="col-md-6 btn-acordion"><a href="<?php echo BASE_URL ?>partida/agregar">Agregar</a></div>
			    	<div class="col-md-6 btn-acordion">	<a href="<?php echo BASE_URL ?>partida/consultar">consultar</a></div>
			    	
			    </div>
			  </div>
			  <h3>Ayudas</h3>
			  <div>
			    <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna. </p>
			  </div>
			  <h3>Estadisticas</h3>
			  <div>
			    <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui. </p>
			    <ul>
			      <li>List item one</li>
			      <li>List item two</li>
			      <li>List item three</li>
			    </ul>
			  </div>
			  <h3>Reportes</h3>
			  <div>
			    <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia mauris vel est. </p><p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
			  </div>
			</div>
		

		</div>

	</div>

